import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import Header from "./component/header";

const arimo = Arimo({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Facebook Clone",
    description: "Generated by Facebook Clone",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={arimo.className}>
                <Header />
                {children}
                <Analytics />
            </body>
        </html>
    );
}
